apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 10
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: brlsistemas/rotten-potatoes:v2
          ports:
            - containerPort: 5000 # porta configurada no Dockerfile
          env: # informações do arquivo app.py
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongo-service # do service.yaml do mongo
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: mongopwd
  
---
# podemos declarar o service aqui também

apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
  